In [44]:
test1 = np.array([1,2,3,4])
test2 = np.array([[1],[2],[3],[4]])

In [45]:
print(test1)
print(test2)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [46]:
print(test1.T)
print(test2.T)
print(test2.T[0][3])

[1 2 3 4]
[[1 2 3 4]]
4


In [47]:
np.c_[test1]

array([[1],
       [2],
       [3],
       [4]])

In [48]:
test3 = np.array([1.4 + 1.0j], dtype=complex)
test4 = np.array([1.4 + 1.0j], dtype=complex)

In [49]:
test3 * test4

array([0.96+2.8j])