In [2]:
import numpy as np

In [44]:
test1 = np.array([1,2,3,4])
test2 = np.array([[1],[2],[3],[4]])

In [45]:
print(test1)
print(test2)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [46]:
print(test1.T)
print(test2.T)
print(test2.T[0][3])

[1 2 3 4]
[[1 2 3 4]]
4


In [47]:
np.c_[test1]

array([[1],
       [2],
       [3],
       [4]])

In [48]:
test3 = np.array([1.4 + 1.0j], dtype=complex)
test4 = np.array([1.4 + 1.0j], dtype=complex)

In [49]:
test3 * test4

array([0.96+2.8j])

In [8]:
test1 = np.array([[1,2]])
test2 = np.array([[2,3]])


In [9]:
test1 * test2

array([[2, 6]])

In [10]:
np.dot(test1, test2)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [15]:
np.multiply(test1, test2.T)

array([[2, 4],
       [3, 6]])

In [12]:
test1.T

array([[1],
       [2]])

In [56]:
c = np.array([[0,1,2,3],[3,4,5,3],[6,7,8,3]])
d = np.array([[5],[6],[7]])

In [50]:
c

array([[0, 1, 2, 3],
       [3, 4, 5, 3],
       [6, 7, 8, 3]])

In [51]:
d

array([[5, 6, 7]])

In [52]:
np.multiply(c,d)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [53]:
np.dot(c,d)

ValueError: shapes (3,4) and (1,3) not aligned: 4 (dim 1) != 1 (dim 0)

In [54]:
np.multiply(d,d)

array([[25, 36, 49]])

In [57]:
np.subtract(c,d.T)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [65]:
c = np.array([[0,1,2,3],[3,4,5,3],[6,7,8,3]])
d = np.array([[5],[6],[7]])
# d = np.array([[5]])

In [70]:
np.multiply(d,d)

array([[25],
       [36],
       [49]])